### ISSUE TITLE
SignInActivity.java line 77

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#45] opened 2014-10-22 09:06 UTC
#### in de.elanev.studip.android.app.backend.net.oauth.SignInActivity.requestTokenReceived

* Number of crashes: 49
* Impacted devices: 48

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/543e3cbce3de5099ba0de6f4](https://crashlytics.com/elanev/android/apps/de.elanev.studip.android.app/issues/543e3cbce3de5099ba0de6f4)

**Comment by mndfcked** [comment] 2015-04-22 15:57
Duplicate of  #40

**Closed by mndfcked** 2015-04-22 15:57 UTC
