### ISSUE TITLE
SQLiteDatabase.java line 0

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#66] opened 2015-04-07 11:03 UTC
#### in net.sqlcipher.database.SQLiteDatabase.dbopen

* Number of crashes: 43
* Impacted devices: 43

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bfca0d65f8dfea15a7caf4](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bfca0d65f8dfea15a7caf4)

**Comment by mndfcked** [comment] 2015-04-22 16:00
Duplicate of #55

**Closed by mndfcked** 2015-04-22 16:00 UTC
