### ISSUE TITLE
CourseDocumentsFragment.java line 446

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#59] opened 2014-12-24 07:05 UTC
#### in de.elanev.studip.android.app.frontend.courses.CourseDocumentsFragment$DocumentsListFragment.downloadDocument

* Number of crashes: 49
* Impacted devices: 17

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5440e060e3de5099ba11d039](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/5440e060e3de5099ba11d039)

**Comment by mndfcked** [comment] 2015-04-22 15:55
Duplicate of #52

**Closed by mndfcked** 2015-04-22 15:55 UTC
