### ISSUE TITLE
CourseDocumentsFragment.java line 167

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#65] opened 2015-03-26 13:30 UTC
#### in de.elanev.studip.android.app.frontend.courses.CourseDocumentsFragment.queryStatus

* Number of crashes: 26
* Impacted devices: 26

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bcf26b65f8dfea15a2e913](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/54bcf26b65f8dfea15a2e913)

**Comment by mndfcked** [comment] 2015-04-22 15:54
Duplicate of #56

**Closed by mndfcked** 2015-04-22 15:54 UTC
