### ISSUE TITLE
SignInActivity.java line 77

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#58] opened 2014-12-15 14:30 UTC
#### in de.elanev.studip.android.app.backend.net.oauth.SignInActivity.requestTokenReceived

* Number of crashes: 49
* Impacted devices: 48

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544e23f5e3de5099ba2472a2](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/544e23f5e3de5099ba2472a2)

**Comment by mndfcked** [comment] 2015-04-22 15:56
Duplicate of  #40

**Closed by mndfcked** 2015-04-22 15:56 UTC
